local pick = require("keystone.pick")
pick.setup()

vim.keymap.set("n", "<leader>ff", "<cmd>Pick files<cr>", { desc = "Find Files"} )
vim.keymap.set("n", "<leader>fp", "<cmd>Pick recent_files<cr>", { desc = "Recent Files"} )
vim.keymap.set("n", "<leader>fg", "<cmd>Pick live_grep<cr>", { desc = "Recent Files"} )
vim.keymap.set("n", "<leader>fc", "<cmd>Pick config_files<cr>", { desc = "Config Files"} )
vim.keymap.set("n", "<leader>fb", "<cmd>Pick buffers<cr>", { desc = "Buffers"} )
vim.keymap.set("n", "<leader>fr", "<cmd>Pick lsp_references<cr>", { desc = "LSP References"} )
vim.keymap.set("n", "<leader>fF", "<cmd>Pick document_functions<cr>", { desc = "Document functions"} )
vim.keymap.set("n", "<leader>fs", "<cmd>Pick spell_suggest<cr>", { desc = "Spell suggestions" })
vim.keymap.set("n", "<leader>fq", "<cmd>Pick quickfix<cr>", { desc = "Quickfix" })
vim.keymap.set("n", "<leader>fj", "<cmd>Pick jumplist<cr>", { desc = "Jumplist" })
vim.keymap.set("n", "<leader>fe", function () require("keystone.pick.pickers.quickfix").open({filter = "errors"}) end, { desc = "Quickfix Errors" })

vim.keymap.set("n", "<leader>fd", "<cmd>Pick document_diagnostics<cr>", { desc = "Document diagnostics"} )
vim.keymap.set("n", "<leader>fD", "<cmd>Pick workspace_diagnostics<cr>", { desc = "Workspace diagnostics"} )
vim.keymap.set("n", "<leader>gd", "<cmd>Pick git_diff<cr>", { desc = "Git diff" })
vim.keymap.set("n", "<leader>gh", "<cmd>Pick git_hunks<cr>", { desc = "Git hunks" })


-- vim.keymap.set("n", "<leader>f?", show_search_root, { desc = "Search dir (for Find/Grep)" })
-- vim.keymap.set("n", "<leader>fa", builtin.resume, { desc = "Resume last search" })
-- vim.keymap.set("n", "<leader>fo", builtin.builtin, { desc = "Show all pickers" })
-- vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Buffers" })
-- 	{ desc = "Find Config File" })
--
-- vim.keymap.set("n", "<leader>ff", function() show_file_picker(true) end, { desc = "Find Files (fuzzy)" })
-- vim.keymap.set("n", "<leader>fF", function() show_file_picker(false) end, { desc = "Find Files (non-fuzzy)" })
--
-- vim.keymap.set("n", "<leader>fg", function() show_grep_picker({ use_regex = false }) end, { desc = "Grep (smart case)" })
-- vim.keymap.set("n", "<leader>fG", function() show_grep_picker({ use_regex = true }) end, { desc = "Grep text (regex)" })
--
-- vim.keymap.set("n", "<leader>fp", builtin.oldfiles, { desc = "Previous files" })
-- vim.keymap.set("n", '<leader>f"', builtin.registers, { desc = "Registers" })
-- vim.keymap.set("n", '<leader>f/', builtin.search_history, { desc = "Search History" })
-- vim.keymap.set("n", "<leader>ft", builtin.current_buffer_fuzzy_find, { desc = "Buffer Lines" })
-- vim.keymap.set("n", "<leader>fh", builtin.command_history, { desc = "Command History" })
-- vim.keymap.set("n", "<leader>fj", builtin.jumplist, { desc = "Jumps" })
-- vim.keymap.set("n", "<leader>fm", builtin.marks, { desc = "Marks" })
-- vim.keymap.set("n", "<leader>fq", builtin.quickfix, { desc = "Quickfix List" })
-- vim.keymap.set("n", "<leader>fe", show_qf_errors, { desc = "Quickfix Errors" })
-- vim.keymap.set("n", "<leader>fD", builtin.diagnostics, { desc = "Workspace Diagnostics (cwd)" })
-- vim.keymap.set("n", "<leader>fB", builtin.live_grep, { desc = "Grep Open Buffers" })
-- vim.keymap.set("n", "<leader>fr", builtin.lsp_references, { desc = "LSP references" })
-- vim.keymap.set("n", "<leader>fS", find_document_symbols, { desc = "LSP references" })
-- vim.keymap.set("n", "<leader>fs", builtin.spell_suggest, { desc = "Spell suggestions" })
-- -- === Git ===
-- vim.keymap.set("n", "<leader>gb", builtin.git_branches, { desc = "Git Branches" })
-- vim.keymap.set("n", "<leader>gl", builtin.git_commits, { desc = "Git Log" })
-- vim.keymap.set("n", "<leader>gL", builtin.git_bcommits, { desc = "Git Log Line" })
-- vim.keymap.set("n", "<leader>gd", builtin.git_status, { desc = "Git diff" })
-- vim.keymap.set("n", "<leader>gS", builtin.git_stash, { desc = "Git stash list" })
-- vim.keymap.set("n", "<leader>gf", builtin.git_files, { desc = "Find Git Files" })
