require("loop-debug").setup({
	enable_dap_log = false
})

vim.keymap.set("n", "<leader>d", "<Nop>", { noremap = true }) -- to avoid deleting text by accident
vim.keymap.set("n", "<leader>bl", ":Loop breakpoint list<CR>", { desc = "List breakpoints", silent = true })
vim.keymap.set("n", "<leader>bb", ":Loop breakpoint toggle<CR>", { desc = "Toggle breakpoints", silent = true })
vim.keymap.set("n", "<leader>bd", ":Loop breakpoint delete<CR>", { desc = "Delete breakpoints", silent = true })
vim.keymap.set("n", "<leader>bc", ":Loop breakpoint conditional<CR>", { desc = "Set conditional breakpoint", silent = true })
vim.keymap.set("n", "<leader>bL", ":Loop breakpoint logpoint<CR>", { desc = "Set logpoint", silent = true })
vim.keymap.set("n", "<leader>bE", ":Loop breakpoint enable_all<CR>", { desc = "Enable all breakpoints", silent = true })
vim.keymap.set("n", "<leader>bD", ":Loop breakpoint disable_all<CR>", { desc = "Disable all breakpoints", silent = true })
vim.keymap.set("n", "<leader>ds", ":Loop debug session<CR>", { desc = "Select debug session", silent = true })
vim.keymap.set("n", "<leader>dt", ":Loop debug thread<CR>", { desc = "Select thread", silent = true })
vim.keymap.set("n", "<leader>df", ":Loop debug frame<CR>", { desc = "Select stack frame", silent = true })
vim.keymap.set("n", "<leader>di", ":Loop debug inspect<CR>", { desc = "Inspect value", silent = true })
vim.keymap.set("n", "<leader>dp", ":Loop debug pause<CR>", { desc = "Pause execution", silent = true })
vim.keymap.set("n", "<leader>dl", ":Loop debug step_in<CR>", { desc = "Step into", silent = true })
vim.keymap.set("n", "<leader>dh", ":Loop debug step_out<CR>", { desc = "Step out", silent = true })
vim.keymap.set("n", "<leader>dj", ":Loop debug step_over<CR>", { desc = "Step over", silent = true })
vim.keymap.set("n", "<leader>dk", ":Loop debug step_back<CR>", { desc = "Step back", silent = true })
vim.keymap.set("n", "<leader>dc", ":Loop debug continue<CR>", { desc = "Continue execution", silent = true })
vim.keymap.set("n", "<leader>dC", ":Loop debug continue_all<CR>", { desc = "Continue debug", silent = true })
vim.keymap.set("n", "<leader>dk", ":Loop debug terminate<CR>", { desc = "Terminate debug", silent = true })
vim.keymap.set("n", "<leader>dK", ":Loop debug terminate_all<CR>", { desc = "Terminate debug", silent = true })
vim.keymap.set("n", "<A-l>", ":Loop debug step_in<CR>", { desc = "Step into", silent = true })
vim.keymap.set("n", "<A-h>", ":Loop debug step_out<CR>", { desc = "Step out", silent = true })
vim.keymap.set("n", "<A-j>", ":Loop debug step_over<CR>", { desc = "Step over", silent = true })
vim.keymap.set("n", "<A-;>", ":Loop debug continue<CR>", { desc = "Step back", silent = true })
vim.keymap.set("n", "<A-b>", ":Loop debug breakpoint toggle<CR>", { desc = "Toggle breakpoints", silent = true })
